name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted]
    env:
      TES: ${{vars.TES}}
    steps:
      - name: Deploy
        run: |
          echo "${{vars.TES}}"
          echo "${TES}"